### ISSUE TITLE
Error during logging

### ISSUE THREAD

**Issue by achew22** [evalphobia/logrus_stackdriver#4]
Is there any way to detect when an issue has occurred in the logging and call a callback where I could increment a prometheus metric? I would like to have an alert fire if my logging starts to fail for some reason but I can't quite make out how to do that.

Thanks!

**Comment by evalphobia** [comment]
@achew22 I'm so sorry for delayed reply. 
So you would like to know and handle when Stackdriver API returns error, right?

I created PR to handle error from Stackdriver.
Is this help you?
https://github.com/evalphobia/logrus_stackdriver/pull/5

**Comment by achew22** [comment]
Looks great! Thanks for doing that

**Comment by evalphobia** [comment]
I tagged it [v0.2.2](https://github.com/evalphobia/logrus_stackdriver/releases/tag/v0.2.2).
If you have any problem to use it, please reopen issue.
